export const SET_LOADING = 'SET_LOADING';

export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';

export const SET_GOOGLEMAPS_AUTOCOMPLETE = 'SET_GOOGLEMAPS_AUTOCOMPLETE';
export const SET_PICKUP_LOCATION = 'SET_PICKUP_LOCATION';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_DATE = 'SET_DATE';